name: 'Test ref inputs' 
description: 'This action is to test the ref inputs' 
inputs:
  github-token: 
    description: 'GitHub token'
    required: true
  ref:
    description: 'The branch, tag, or SHA to checkout. Defaults to the head ref of the pull request that triggered the workflow.'
    required: false
    default: ${{ github.event.pull_request.head.ref }}
  repository:
    description: 'The full name of the repository to checkout (in owner/repo format). Defaults to the repository containing the pull request that triggered the workflow.'
    required: false
    default: ${{ github.event.pull_request.head.repo.full_name }}
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.github-token }}
    - name: test ref inputsi
      run: |
        echo "ref: ${{ inputs.ref }}"
        echo "repository: ${{ inputs.repository }}"
