name: Create PR

on:
  workflow_dispatch:

jobs:
  test:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
# Setups the environment
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      - name: Set git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"
      - name: Create file
        run: date >> time.txt
      - name: Add and Commit
        run: |
          git checkout -b new_branch
          git add time.txt
          git commit -m "Commit time"
          git push origin new_branch
      - name: Commit and Push (PERSONAL ACCESS TOKEN)
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ADMIN_GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"new_branch","base":"main"}'
