name: Fail

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  fail:
    name: Fail
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
